export const allOrganizations = [
  `(un)Jaded`,
  `32º Figure Skating Club`,
  `825th Cadet Wing Special Warfare Club`,
  `ADAPT Texas`,
  `ADPRos`,
  `AIESEC in Austin`,
  `ATX KDC`,
  `ATX Science Olympiad`,
  `AWAKE (Anointed Worship Awakes Koreans and Everyone)`,
  `Absolute Pitch`,
  `Absolute Texxas`,
  `Academic Counselors Association`,
  `Academy of Managed Care Pharmacy at UT Austin`,
  `Access Christian Fellowship`,
  `Action Committee for Career Services`,
  `Active Minds at The University of Texas at Austin`,
  `Acts College Fellowship`,
  `Actuarial Science Club`,
  `Adventist Christian Fellowship at UT Austin`,
  `African Students Organization`,
  `Afrikan-American Affairs`,
  `Afterglow ATX`,
  `Allied Scholars for Animal Protection at The University of Texas at Austin`,
  `Alpha Chi Omega`,
  `Alpha Delta Pi`,
  `Alpha Epsilon Delta - Pre-Health Honor Society`,
  `Alpha Epsilon Phi`,
  `Alpha Epsilon Pi Fraternity`,
  `Alpha Kappa Alpha Sorority, Incorporated`,
  `Alpha Kappa Psi - Prof. Bus. Frat.`,
  `Alpha Lambda Delta Phi Eta Sigma - Freshmen`,
  `Alpha Lambda Mu at UT Austin`,
  `Alpha Omega`,
  `Alpha Phi`,
  `Alpha Phi Alpha Fraternity, Inc.`,
  `Alpha Phi Omega`,
  `Alpha Phi Sigma - Pre Health Honors Society`,
  `Alpha Sigma Rho Sorority`,
  `Alpha Xi Delta`,
  `Alternative Breaks - Student Chapter`,
  `Always Texas`,
  `American Academy of Environmental Engineers and Scientists at the University of Texas`,
  `American Association of Petroleum Geologists- Longhorn Chapter`,
  `American Association of Pharmaceutical Scientists at the University of Texas at Austin- Student Chapter`,
  `American Chemical Society - Student Affiliates`,
  `American Institute of Aeronautics and Astronautics`,
  `American Institute of Chemical Engineers`,
  `American Journal of Criminal Law`,
  `American Library Association Student Chapter`,
  `American Marketing Association, UT Collegiate Chapter`,
  `American Medical Student Association - Pre-med`,
  `American Muslim Women Physicians Association at UT`,
  `American Nuclear Society`,
  `American Red Cross Club at The University of Texas at Austin`,
  `American Society for Biochemistry and Molecular Biology Student Chapter at the University of Texas at Austin`,
  `American Society for Microbiology at The University of Texas at Austin`,
  `American Society of Civil Engineers`,
  `American Society of Landscape Architects Student Chapter (ASLA)`,
  `American Society of Mechanical Engineers`,
  `Animators Club`,
  `Anime Club`,
  `Apricity Magazine`,
  `Arab Students Association`,
  `Architectural Engineering Institute`,
  `Arnold Air Society`,
  `Arrows of Christ`,
  `Art Education Workshops and Development`,
  `Asian American Campus Ministry`,
  `Asian American Journalists Association at UT`,
  `Asian Business Students Association`,
  `Asian Desi Pacific Islander American Collective`,
  `Asian Pacific American Law Student Association`,
  `Asian Pharmacy Students Association`,
  `Asian/Asian American Faculty and Staff Association`,
  `Assault & Flattery`,
  `Association for Computing Machinery`,
  `Association for Women in Mathematics - Texas Chapter`,
  `Association of Black Computer Scientists`,
  `Association of Computational Engineers`,
  `Association of Latino Professionals For America`,
  `Atidna at the University of Texas`,
  `Austin Alternative Protein Project`,
  `Austin Chinese Campus Christian Fellowship`,
  `Austin Collegiate DECA`,
  `Austin Korean Presbyterian Church Psalm Young Adults`,
  `Austin Life Church Students Chapter`,
  `Austin STEM Buddies`,
  `Austin Student Chapter of the Acoustical Society of America`,
  `Austin Students for a Democratic Society`,
  `Austin Sunshine Camps at The University of Texas at Austin`,
  `Ayn Rand Club at the University of Texas`,
  `B-Boy Session`,
  `Balkan Student Union`,
  `Bangladeshi Students Association at the University of Texas at Austin`,
  `Baptist Student Ministry`,
  `Beauties and the Beat`,
  `Because Inquiry Propels Our Curiosity`,
  `Beekeeping Society`,
  `Bengali Students Association`,
  `Best Buddies`,
  `Beta Beta Beta Biological Honor Society`,
  `Beta Theta Pi at the University of Texas at Austin`,
  `Beta Upsilon Chi- Brothers Under Christ`,
  `Bhakti Yoga Club`,
  `Bilingual Education Student Organization`,
  `Bioethics Society at the University of Texas at Austin`,
  `Biomedical Engineering Graduate Student Society`,
  `Biomedical Engineering Society`,
  `Biomedical Optics Graduates Organization`,
  `Biomedical Outreach and Leadership Team`,
  `Black Business Student Association`,
  `Black Graduate Student Association`,
  `Black Health Professions Organization- MAPS Chapter`,
  `Black Homecoming Planning Committee`,
  `Black Muslims Alliance`,
  `Black Student Alliance`,
  `Black Student Alliance's Freshman Action Team`,
  `Black Student Media Association`,
  `Black Studies Graduate Student Organization`,
  `Black Women Wellness Organization`,
  `Blanton Museum of Art`,
  `Blue Longhorns`,
  `Board Fellows`,
  `Board of Advocates - Law School`,
  `Brazilian Jiu Jitsu at the University of Texas`,
  `BridgeTexas`,
  `Bridges International - Texas Chapter`,
  `Broccoli Project`,
  `Buddha's Light International Association- Austin Young Adult Division- Longhorn Chapter`,
  `Business Analytics Association`,
  `Business Ethics Team`,
  `CHYK West at the University of Texas at Austin`,
  `CS Roadshow`,
  `Cactus Yearbook`,
  `Caduceus`,
  `Calyx Magazine`,
  `Camp Kesem at the University of Texas at Austin`,
  `Campus Cat Coalition`,
  `Campus Elections`,
  `Campus Environmental Center`,
  `Campus Events + Entertainment`,
  `Campus Events + Entertainment African American Culture`,
  `Campus Events + Entertainment Asian American Culture`,
  `Campus Events + Entertainment Creative Arts and Theatre`,
  `Campus Events + Entertainment Distinguished Speakers`,
  `Campus Events + Entertainment Events CoSponsorship Board`,
  `Campus Events + Entertainment Headliners`,
  `Campus Events + Entertainment Mexican American Culture`,
  `Campus Events + Entertainment Recreation`,
  `Campus Events + Entertainment Showtime`,
  `Campus Events + Entertainment Texas Traditions`,
  `Catholic Law Student Society`,
  `Center for Asian American Studies`,
  `Center for Community Engagement`,
  `Central American Student Association`,
  `Central Texas Model United Nations`,
  `Chabad Jewish Student Organization`,
  `Change1`,
  `Chemistry Student Safety Organization`,
  `Chess Run Club`,
  `Chi Beta Delta Service Sorority`,
  `Chi Kappa Phi Service Society`,
  `Chi Omega Sorority`,
  `Chicano/Hispanic/Latino Law Students' Association`,
  `Chinese Student Association`,
  `Chinese Students and Scholars Association`,
  `Christian Legal Society`,
  `Christian Students on Campus`,
  `Circle K International`,
  `Clean Tech Group at McCombs`,
  `ClockTower Cultural Productions`,
  `Club Golf`,
  `Club Tennis`,
  `Clutch`,
  `Collaborative Artists`,
  `College Republicans at Texas`,
  `College at the Austin Stone`,
  `College of Education Council`,
  `College of Fine Arts`,
  `College of Natural Sciences Peer Leader Academy`,
  `College of Psychiatric and Neurologic Pharmacists, University of Texas at Austin Collegiate Chapter`,
  `Collegium Musicum`,
  `Communication Council`,
  `Communication and Leadership Club`,
  `Council for Genetics Education`,
  `Council of Graduate Chemists`,
  `Crafter's Circle`,
  `Creative Art Collective`,
  `Crochet 4 a Cause`,
  `Cross Training Club at the University of Texas`,
  `Crossroads`,
  `Cybersecurity Society at The University of Texas at Austin`,
  `Dance Action`,
  `David's Spirit`,
  `Deaf Culture Alliance at the University of Texas at Austin`,
  `Dean's Scholars Student Association`,
  `Dean's Squad`,
  `Dell Medical School Pre-Health & Diversity Scholars`,
  `Delta Delta Delta`,
  `Delta Epsilon Mu-Sigma Chapter`,
  `Delta Epsilon Psi Fraternity, Inc`,
  `Delta Gamma`,
  `Delta Sigma Phi Fraternity`,
  `Delta Sigma Pi`,
  `Delta Sigma Theta Sorority, Inc.`,
  `Delta Tau Delta`,
  `Delta Theta Mu`,
  `Delta Upsilon`,
  `Desi Students of Texas`,
  `Dialogue Student Association`,
  `Disability Advocacy Student Coalition`,
  `Disability Inclusion Agency of Student Government`,
  `Disability and Access`,
  `Discovery Scholars Program`,
  `Discovery, Immersion, Visualization, & Experiences Club (DIVE)`,
  `Disneyy Club Texas`,
  `Diversity and Inclusion Agency of Student Government`,
  `Diversity in Advertising & PR`,
  `DoS Graduate Assistants`,
  `Dog Socialization Club at UT Austin`,
  `Dream Corps at the University of Texas at Austin`,
  `Drift Magazine ATX`,
  `EERI (Earthquake Engineering Research Institute)`,
  `ERROR AT INDEX 1014`,
  `ERROR AT INDEX 110`,
  `ERROR AT INDEX 128`,
  `ERROR AT INDEX 15`,
  `ERROR AT INDEX 165`,
  `ERROR AT INDEX 178`,
  `ERROR AT INDEX 185`,
  `ERROR AT INDEX 189`,
  `ERROR AT INDEX 209`,
  `ERROR AT INDEX 221`,
  `ERROR AT INDEX 222`,
  `ERROR AT INDEX 223`,
  `ERROR AT INDEX 226`,
  `ERROR AT INDEX 235`,
  `ERROR AT INDEX 236`,
  `ERROR AT INDEX 238`,
  `ERROR AT INDEX 255`,
  `ERROR AT INDEX 262`,
  `ERROR AT INDEX 273`,
  `ERROR AT INDEX 291`,
  `ERROR AT INDEX 308`,
  `ERROR AT INDEX 324`,
  `ERROR AT INDEX 329`,
  `ERROR AT INDEX 365`,
  `ERROR AT INDEX 378`,
  `ERROR AT INDEX 441`,
  `ERROR AT INDEX 452`,
  `ERROR AT INDEX 507`,
  `ERROR AT INDEX 527`,
  `ERROR AT INDEX 541`,
  `ERROR AT INDEX 553`,
  `ERROR AT INDEX 598`,
  `ERROR AT INDEX 601`,
  `ERROR AT INDEX 611`,
  `ERROR AT INDEX 618`,
  `ERROR AT INDEX 670`,
  `ERROR AT INDEX 672`,
  `ERROR AT INDEX 681`,
  `ERROR AT INDEX 691`,
  `ERROR AT INDEX 770`,
  `ERROR AT INDEX 782`,
  `ERROR AT INDEX 784`,
  `ERROR AT INDEX 803`,
  `ERROR AT INDEX 81`,
  `ERROR AT INDEX 817`,
  `ERROR AT INDEX 819`,
  `ERROR AT INDEX 82`,
  `ERROR AT INDEX 839`,
  `ERROR AT INDEX 843`,
  `ERROR AT INDEX 882`,
  `ERROR AT INDEX 89`,
  `ERROR AT INDEX 895`,
  `ERROR AT INDEX 938`,
  `ERROR AT INDEX 940`,
  `ERROR AT INDEX 948`,
  `ERROR AT INDEX 954`,
  `ERROR AT INDEX 971`,
  `ERROR AT INDEX 975`,
  `East Asia Business Association at the University of Texas at Austin`,
  `Effective Altruism at University of Texas at Austin`,
  `Election Supervisory Board`,
  `Electrical Computer Engineering and Business Association`,
  `Electronic Game Developers Society`,
  `Elevate Student Fellowship`,
  `Emancipet on Campus`,
  `Emergency Contraception for Every Campus`,
  `Engineering Chamber Orchestra`,
  `Engineering LGBQTies`,
  `Engineering and Computational Learning of Artificial Intelligence in Robotics`,
  `Engineers for a Sustainable World`,
  `Environmental Justice and Eco-Therapy Student Organization`,
  `Environmental Law Society`,
  `Epic Movement`,
  `Episcopal Campus Ministry`,
  `Epsilon Nu Tau- Phi Collegiate Chapter`,
  `Eta Kappa Nu: Electrical Engineering`,
  `Eta Sigma Phi`,
  `Every Nation Campus`,
  `Expand Medical Borders`,
  `Feminist Action Project`,
  `Field Education and Development: Undergraduate/Graduate Placements (FED UP) Coalition`,
  `Fika ATX`,
  `Filipino Students Association`,
  `Fine Arts Council`,
  `First Generation Law Students`,
  `First-Year Leadership Organization of Student Government`,
  `Foot in the Door Theatre`,
  `Forever Texas`,
  `Freetail Hackers`,
  `French and Italian Graduate Student Organization`,
  `Freshman Launch`,
  `Freshman Leaders in Progress`,
  `Friar Society`,
  `Friends of CAMP at the University of Texas at Austin`,
  `Friends of MSF at UT Austin`,
  `Front 'N Center`,
  `Fuse A Cappella`,
  `Future Doctors of America`,
  `GAIN Health at Texas`,
  `GSC Student Leadership Committee`,
  `Gamma Beta Fraternity, Inc.`,
  `Gamma Iota Sigma @ UT Austin`,
  `Gamma Rho Lambda`,
  `Gender Minorities in Physics`,
  `Gender Violence Law Caucus`,
  `Geo-Institute`,
  `Getting Radical In The South`,
  `Gigglepants Improv Comedy Troupe`,
  `Girl Up at the University of Texas at Austin`,
  `GirlAdvocates!`,
  `Girls Who Code College Loops at UT Austin`,
  `Global Macro Team`,
  `Global Medical Brigades`,
  `Global Medical Missions Alliance`,
  `Global Medical Training`,
  `Governmental Relations Agency of Student Government`,
  `Grad InterVarsity Christian Fellowship`,
  `Graduate Association for Germanic-Language Students`,
  `Graduate Business Council`,
  `Graduate ECE`,
  `Graduate Engineering Council`,
  `Graduate Ladies of Aerospace and Mechanics`,
  `Graduate Marketing Network`,
  `Graduate Nursing Student Association`,
  `Graduate Organization for Comparative Literature Students`,
  `Graduate Public Affairs Council`,
  `Graduate Student Art History Association`,
  `Graduate Student Assembly`,
  `Graduate Student Organization Construction Engineering and Project Management`,
  `Graduate Undergraduate Research Union`,
  `Graduates for Underrepresented Minorities`,
  `HISPANIC FACULTY STAFF ASSOCIATION (HFSA)`,
  `HOSA- Future Health Professionals`,
  `Habitat for Humanity Campus Chapter`,
  `Haven Student Fellowship`,
  `Healing with Harmonies`,
  `Health Careers Mentorship Program`,
  `Health Informatics Organization`,
  `Health Science Honors Council`,
  `Healthyhorns Peer Educators`,
  `Heartfulness Meditation Group`,
  `Hearts for the Homeless Austin`,
  `Helping Hornz`,
  `Heman Sweatt Center for Black Males`,
  `Her Campus at Texas`,
  `Hill House Students`,
  `Hindu Students Association`,
  `Hindu YUVA`,
  `Hispanic Association of Computer Scientists`,
  `Hispanic Association of Pharmacists`,
  `Hispanic Business Student Association`,
  `Hispanic Nursing Student Association`,
  `Hong Kong Students Association`,
  `Honors Business Association`,
  `Hook 'Em Arts`,
  `Hook the Vote Agency of Student Government`,
  `Hook'd Magazine`,
  `Hooked On Skin Care`,
  `Horns for Life`,
  `Hum A Cappella`,
  `Human Dimensions of Organizations Undergraduate Organization`,
  `Human Rights Law Society`,
  `Humanity First - Texas Chapter`,
  `Hunger and Homelessness Outreach`,
  `ICMA at the University of Texas`,
  `IEEE Power and Energy Society`,
  `IEEE Robotics and Automation Society`,
  `IEEE TEMS Graduate Student Chapter - Central Texas Section`,
  `IFORTY Administrative Professional Network`,
  `INFORMS Student Chapter at The University of Texas at Austin`,
  `ISPOR`,
  `If/When/How Texas Law`,
  `Ignite Texas`,
  `In Between the Lines`,
  `Indian Cultural Association`,
  `Indian Students Association`,
  `Indonesian Student Association (PERMIAS)`,
  `Information and Systems Security Society (ISSS)`,
  `Institute of Electrical & Electronics Engineers`,
  `Institute of Transportation Engineers`,
  `Intellectual Property Law Society`,
  `InterVarsity Christian Fellowship`,
  `Interfraternity Council`,
  `International Affairs Society`,
  `International Association of Drilling Contractors at the University of Texas at Austin`,
  `International Business Student Association`,
  `International Graduate Student Ministry - at Austin`,
  `International Relations and Global Studies Council`,
  `International Students Agency of Student Government`,
  `International Undergraduate Student Ministry-Austin`,
  `Iranian Students Academic and Cultural Organization`,
  `Ismaili Muslim Students Association`,
  `J. Reuben Clark Law Society`,
  `Jackson School of Geosciences`,
  `Japanese Association`,
  `Jeeyar International Youth Association`,
  `Jewish Legal Society`,
  `Joshua Church at UT Austin`,
  `Journalism Graduate Student Council`,
  `K-pop Beat`,
  `KVRX Student Radio`,
  `Kappa Alpha Order`,
  `Kappa Alpha Psi Fraternity, Inc.`,
  `Kappa Alpha Theta`,
  `Kappa Delta`,
  `Kappa Delta Chi Sorority, Incorporated`,
  `Kappa Epsilon - Pharmacy`,
  `Kappa Kappa Gamma`,
  `Kappa Kappa Psi`,
  `Kappa Phi Gamma Sorority, Inc.`,
  `Kappa Phi Lambda Sorority, Inc.`,
  `Kappa Rho Pre-Medical Honors Society`,
  `Kappa Sigma Fraternity`,
  `Kappa Theta Pi at the University of Texas at Austin`,
  `Kendra Scott Women's Entrepreneurial Leadership Institute Student Board`,
  `Kinesiology Club`,
  `Koinonia Christian Fellowship`,
  `Kontrol Crew Texas`,
  `Korean American Student Association at Austin`,
  `Korean Music Association`,
  `LC Living Hope Ministry`,
  `La Fe (Latino Fellowship)`,
  `La Unidad Latina Interest Group`,
  `Labyrinth Progressive Student Ministry`,
  `Lambda Chi Alpha Fraternity`,
  `Lambda Phi Epsilon Fraternity, Inc.`,
  `Lambda Theta Alpha Latin Sorority Incorporated`,
  `Lang Stuttering Institute Student Leadership Organization`,
  `Last Writers at the University of Texas at Austin`,
  `Latin American and Hispanic Master of Business Association`,
  `Latin Economics and Business Association`,
  `LatinX Graduate Student Association at UT Austin`,
  `Latina/x and Indigenous Leadership Institute`,
  `Latinx Community Affairs`,
  `Latinx Health Professions Organization`,
  `Law Students For Black Lives`,
  `Lebanese Cultural Organization`,
  `Legislative Student Organizations`,
  `Liberal Arts Council`,
  `Liberal Arts Honors Music Ensemble`,
  `Liberal Arts Honors Student Council`,
  `Liberal Arts Pre-Med Society`,
  `Lions Club at the University of Texas at Austin`,
  `Longhorn Alliance for Refugees and Asylees`,
  `Longhorn American Association of Petroleum Geologists Student Chapter`,
  `Longhorn Art Therapy Club`,
  `Longhorn Athletic Training Student Association`,
  `Longhorn Bakers`,
  `Longhorn Band Student Association`,
  `Longhorn Baseball Club`,
  `Longhorn Business Reading Club`,
  `Longhorn Car Club`,
  `Longhorn Catholic Council`,
  `Longhorn Chi Alpha Christian Fellowship`,
  `Longhorn Christian Fellowship`,
  `Longhorn Comic Books`,
  `Longhorn Cubing Club`,
  `Longhorn Dance Club`,
  `Longhorn EMS Agency of Student Government`,
  `Longhorn Energy Club`,
  `Longhorn Furries`,
  `Longhorn Gaming`,
  `Longhorn Hellraisers`,
  `Longhorn Legislative Aide Agency of Student Government`,
  `Longhorn Link Program`,
  `Longhorn LoveWorld`,
  `Longhorn Macro Investors`,
  `Longhorn Magic`,
  `Longhorn Malayali Student Association`,
  `Longhorn Melee`,
  `Longhorn Middle Eastern Cooking Club`,
  `Longhorn Mycological Society`,
  `Longhorn Powerlifting`,
  `Longhorn Pre-Pharmacy Association`,
  `Longhorn Puzzle Club`,
  `Longhorn Quidditch`,
  `Longhorn Quiz Bowl`,
  `Longhorn Racing`,
  `Longhorn Riichi`,
  `Longhorn SHARE Connections`,
  `Longhorn Scholars Program`,
  `Longhorn Singers`,
  `Longhorn Smash`,
  `Longhorn Social Dance`,
  `Longhorn Special Operations Club`,
  `Longhorn Squash Club`,
  `Longhorn Supply Chain`,
  `Longhorn Swim Club`,
  `Longhorn Voices Book Club`,
  `Longhorn Westies`,
  `Longhorn Wrestling`,
  `Longhorn Yoga`,
  `Longhorn for Harm Reduction`,
  `Longhorns For Christ`,
  `MBA Soccer Club`,
  `MEDLIFE at The University of Texas at Austin`,
  `MOVE Texas at UT`,
  `Machine Learning and Data Science`,
  `Management Information Systems Association`,
  `Mandarin Chinese Christian Fellowship`,
  `Marine Science Club`,
  `Math Club`,
  `Mechanical Engineering Graduate Student Board`,
  `Mental Health Agency of Student Government`,
  `Minorities in Education`,
  `Minority Women Pursuing Law`,
  `Miracle Messages Austin`,
  `Mu Delta Alpha @UT Austin`,
  `Mu Epsilon Theta Sorority`,
  `Mu Rho Chapter of Phi Beta Sigma Fraternity Incorporated`,
  `Mujer Latina`,
  `Multicultural Greek Council`,
  `Muslim Legal Society`,
  `Muslim Students' Association`,
  `National Alliance on Mental Illness (NAMI) On Campus at University of Texas at Austin`,
  `National Community Oncology Dispensing Association at the University of Texas`,
  `National Community Pharmacists Association`,
  `National Pan-Hellenic Council`,
  `National Retail Federation Student Association at UT Austin`,
  `National Society of Black Engineers`,
  `National Student Speech, Language and Hearing Association`,
  `Native American & Indigenous Collective`,
  `Native American and Indigenous Peoples Association`,
  `Natural Sciences Council`,
  `Nepali Student Association- Longhorn Chapter`,
  `Neuroscience Graduate Students' Association`,
  `New Wave Longhorns`,
  `New Works Student Council`,
  `Not On My Campus, UT Chapter`,
  `Noteworthy A Cappella`,
  `Nritya Sangam Indian Dance Troupe`,
  `Nurses Christian Fellowship - UT Austin`,
  `ORANGE Magazine`,
  `OUTLaw - LGBTQ Law Student Association`,
  `OUTreach at the University of Texas`,
  `Occupy Campus Ministry at the University of Texas at Austin`,
  `Office of Admissions`,
  `Office of the Dean of Students`,
  `Olivet Bible Fellowship`,
  `Omega Chi Epsilon - Chemical Engineering`,
  `Omega Delta Phi Fraternity, Inc.`,
  `Omega Phi Gamma Fraternity`,
  `OneWay South Asian InterVarsity`,
  `Opportunities for Undergraduate Research at UT Austin`,
  `Opportunities for Undergraduate Research at UT Austin Student Mentors`,
  `Orange Bike Project`,
  `Origami Circle`,
  `Orthodox Christian Campus Ministries at UT Austin`,
  `PPP Graduate Student Alliance`,
  `Palestine Solidarity Committee`,
  `Partners in Health Engage at UT Austin`,
  `Persian Student Society`,
  `Petroleum Graduate Student Association`,
  `Pharmacy Council`,
  `Pharmacy Graduate Students Association`,
  `Phi Alpha Theta, Beta Alpha Chapter - History`,
  `Phi Chi Theta`,
  `Phi Delta Chi`,
  `Phi Delta Phi Pre-Law Honor Society`,
  `Phi Delta Theta Fraternity`,
  `Phi Gamma Delta Fraternity`,
  `Phi Gamma Nu Epsilon Beta`,
  `Phi Kappa Psi Fraternity`,
  `Phi Kappa Sigma`,
  `Phi Kappa Tau`,
  `Phi Lambda Sigma - Pharmacy`,
  `Philosophy & Theory at UT Austin`,
  `Pi Beta Phi`,
  `Pi Kappa Alpha Fraternity`,
  `Pi Lambda Chi Latina Sorority, Inc. - Eta Chapter`,
  `Pi Sigma Pi - Minority Academic Engineering Society`,
  `Plan II Students Association`,
  `Planet Longhorn`,
  `Platypus Austin`,
  `Polish Club at UT`,
  `Polymathic Scholars Student Leadership Panel`,
  `Pre-Law Division of The National Black Law Students Association/ Longhorn Chapter`,
  `Pre-Optometry Professional Society`,
  `Pre-Physician Assistant Society`,
  `Pre-Veterinary Association`,
  `Present Your PhD to a 12-Year-Old`,
  `Pride and Equity Faculty Staff Association`,
  `Private Equity and Venture Capital Club`,
  `Project Sunshine at the University of Texas at Austin`,
  `Project Yellow at the University of Texas at Austin`,
  `Public Defense Group`,
  `Public Interest Law Association`,
  `Public Relations Student Society of America`,
  `Punjabbawockeez`,
  `Q++`,
  `Queer Business Student Association`,
  `Queer Policy Coalition`,
  `Queer Trans Black Indigenous People of Color Agency (QTBIPOCA)`,
  `Queer Trans Student Alliance Agency of Student Government`,
  `RGV Familia Student Organization`,
  `Re:Sound A Cappella`,
  `Readying Impactful Student Entrepreneurs`,
  `Redefined Dance Company`,
  `Reformed University Fellowship`,
  `Reformed University Fellowship International at the University of Texas at Austin`,
  `Reggaeton Dance Club at UT`,
  `Residence Hall Program Team`,
  `Resident Assistant Association`,
  `Rho Chi Pharmaceutical Honor Society`,
  `Ridgetop College`,
  `Ronald E. McNair Scholars Program`,
  `Roustabouts Dance Company`,
  `Runway of Dreams Foundation at The University of Texas at Austin`,
  `SCORE Athletics`,
  `SKY Meditation and Wellness`,
  `SNAFU Improv`,
  `STEEL Dance Company`,
  `Saaya Dance Company`,
  `Safety Education Program`,
  `San Antonio Student Pharmacists Association`,
  `Saudi Students Association`,
  `School of Human Ecology`,
  `School of Human Ecology Ambassadors`,
  `SciCo USA`,
  `Science Under the Stars`,
  `Secular Student Alliance Austin, Texas Chapter`,
  `Sehath`,
  `Senate of College Councils`,
  `Seva Charities`,
  `She's the First at the University of Texas at Austin`,
  `Sigma Alpha Mu Fraternity`,
  `Sigma Chi`,
  `Sigma Delta Lambda Sorority, Inc.`,
  `Sigma Gamma Rho Sorority Inc. Mu Upsilon`,
  `Sigma Lambda Alpha Sorority, Inc.`,
  `Sigma Lambda Beta-Eta Alpha Chapter`,
  `Sigma Lambda Gamma National Sorority`,
  `Sigma Phi Epsilon Fraternity`,
  `Sigma Phi Lambda`,
  `Sigma Phi Omega Sorority, Inc.`,
  `Sikh Students Association`,
  `Silk Club`,
  `Silver Spurs`,
  `Social Anime Club`,
  `Social Entrepreneurship Learning Lab Fellowship`,
  `Society for Advancement of Chicano/Hispanics and Native Americans in Science`,
  `Society for Advancing Gender Equity in STEM`,
  `Society of American Archivists`,
  `Society of Asian Scientists and Engineers`,
  `Society of Hispanic Professional Engineers`,
  `Society of Petroleum Engineers`,
  `Society of Physics Students`,
  `Society of Women Engineers`,
  `Socks for the Sole`,
  `Sorority and Fraternity Life`,
  `Spark Magazine`,
  `Special Olympics Club at The University of Texas`,
  `Spikes at the University of Texas at Austin`,
  `Squad Sonrisas`,
  `Student Academy of Audiology chapter at The University of Texas at Austin`,
  `Student Activities`,
  `Student Animal Legal Defense Fund at the University of Texas at Law School`,
  `Student Association for the School of Information`,
  `Student Bar Association`,
  `Student Chapter of the Biophysical Society at UT`,
  `Student College of Clinical Pharmacy at The University of Texas at Austin`,
  `Student Community of Asian Nurses`,
  `Student Emergency Services`,
  `Student Endowed Centennial Lectureship`,
  `Student Engineering Council`,
  `Student Engineers Educating Kids`,
  `Student Government`,
  `Student Health Advisory Committee`,
  `Student Industry Pharmacists Organization`,
  `Student National Pharmaceutical Association`,
  `Student Parent Organization`,
  `Student Veterans Association`,
  `Students Expanding Austin Literacy`,
  `Students Fighting Climate Change`,
  `Students Making Impacts Through Love & Empathy`,
  `Students for Planned Parenthood`,
  `Students in Medical Laboratory Science`,
  `StudentsCare at University of Texas at Austin`,
  `Studio Art Graduate Association`,
  `Study Abroad`,
  `Supply Chain Management Student Organization`,
  `Switch Energy Club Longhorn Chapter`,
  `Synapse`,
  `TAMID Group at UT`,
  `TCA Chinese Campus Fellowship`,
  `TEDxUTAustin`,
  `THE SEED at The University of Texas at Austin`,
  `TX Human Development and Family Sciences`,
  `TX MedstART`,
  `TX Votes`,
  `Taiwanese American Students Association`,
  `Taiwanese International Student Association`,
  `Taiwanese Student Association`,
  `Take the Wheel Productions`,
  `Tau Beta Pi - Engineering`,
  `Tau Kappa Epsilon Fraternity`,
  `Teachers of Tomorrow`,
  `Teaching Refugees to Understand English at UT Austin`,
  `Teens Thrive`,
  `Terry Scholar Student Association`,
  `Test Org`,
  `TexASHRAE`,
  `Texas 180 Degrees Consulting`,
  `Texas 4000 for Cancer`,
  `Texas Aerial Robotics`,
  `Texas Ahlul Bayt Student Organization`,
  `Texas Angels`,
  `Texas Argentine Tango`,
  `Texas Army ROTC`,
  `Texas Asian Pan-Hellenic Council`,
  `Texas Athletics`,
  `Texas Ballet Club`,
  `Texas Ballroom`,
  `Texas Baseball Diamonds`,
  `Texas Belles Event Planning Organization`,
  `Texas Black Lens`,
  `Texas Blazers`,
  `Texas Blockchain`,
  `Texas Blood Brigade`,
  `Texas Bluebonnets`,
  `Texas Brain Exercise Initiative`,
  `Texas Business Healthcare Association`,
  `Texas Business Leaders`,
  `Texas Civil Discourse`,
  `Texas Computer Science Transfers' Society`,
  `Texas Consulting`,
  `Texas Convergent`,
  `Texas Creative Collective`,
  `Texas Creative Union Project`,
  `Texas Crew`,
  `Texas Cricket Club`,
  `Texas Crohn's and Colitis Initiative`,
  `Texas Cru`,
  `Texas Cycling`,
  `Texas Darlins`,
  `Texas Design Journal`,
  `Texas Design, Build, Fly`,
  `Texas Dhoom`,
  `Texas DiasPRA`,
  `Texas Disc Golf`,
  `Texas DnD`,
  `Texas Dollar For`,
  `Texas Dragon/Lion Dance Team`,
  `Texas Ecology, Evolution, and Behavior Club`,
  `Texas Economics Association`,
  `Texas Economics Journal`,
  `Texas Education Policy Club`,
  `Texas Electronic Music Club`,
  `Texas Enactus`,
  `Texas Energy Capital`,
  `Texas Energy Finance Group`,
  `Texas Engineering World Health`,
  `Texas Environmental Law Journal`,
  `Texas Equestrian Team`,
  `Texas Equity Group`,
  `Texas Federalist Society`,
  `Texas Field Hockey`,
  `Texas Finance Team`,
  `Texas Financial Derivatives`,
  `Texas Fish Club`,
  `Texas Folklorico Dance Company`,
  `Texas Fuego`,
  `Texas Gospel Fellowship`,
  `Texas Guadaloop`,
  `Texas Gymnastics`,
  `Texas Handball`,
  `Texas Health Promotion Club`,
  `Texas Healthcare Law Society`,
  `Texas Healthy Habits`,
  `Texas Hillel`,
  `Texas Hispanic Journal of Law and Policy`,
  `Texas Horizons`,
  `Texas Ice Hockey`,
  `Texas Infinites`,
  `Texas Intellectual Property Law Journal`,
  `Texas Interdisciplinary Plan Mentor Academy`,
  `Texas International Law Journal`,
  `Texas Iron Spikes`,
  `Texas Journal of Oil, Gas, and Energy Law Society`,
  `Texas Journal on Civil Liberties & Civil Rights`,
  `Texas Judo`,
  `Texas Juggling Society`,
  `Texas Lassos`,
  `Texas Latin Dance`,
  `Texas Latinos in Engineering and Sciences`,
  `Texas Law Art Association`,
  `Texas Law Disability and Neurodivergent Alliance`,
  `Texas Law Fellowships`,
  `Texas Law Review`,
  `Texas Law Students for Life`,
  `Texas Law Veterans Association`,
  `Texas Law Women's Christian Fellowship`,
  `Texas Lonestars`,
  `Texas Mahjong Club`,
  `Texas Majorettes`,
  `Texas Men's Lacrosse`,
  `Texas Men's Volleyball`,
  `Texas Men's Water Polo`,
  `Texas Middle Eastern and North African Law Students' Association`,
  `Texas Mohini Dance Team`,
  `Texas Music Producers`,
  `Texas Novas`,
  `Texas Nutrition at the University of Texas at Austin`,
  `Texas Orange Jackets`,
  `Texas Pakistani Students Association`,
  `Texas Pearls`,
  `Texas Phi Delta Epsilon`,
  `Texas Pre-Dental Society`,
  `Texas Pre-Occupational Therapy Community`,
  `Texas Pre-Physical Therapy Society`,
  `Texas Product Engineering Organization`,
  `Texas Public Health`,
  `Texas Queer Union`,
  `Texas Raas`,
  `Texas Real Estate Law Society`,
  `Texas Rising at the University of Texas at Austin`,
  `Texas Robotics Graduate Students`,
  `Texas Rock Climbing`,
  `Texas Royals`,
  `Texas Rugby`,
  `Texas Running Club`,
  `Texas Sigma Alpha Omega`,
  `Texas Society Of Unconventional Drummers`,
  `Texas Space Law & Policy Society`,
  `Texas Spirits`,
  `Texas Stock Team`,
  `Texas Striking Laboratory`,
  `Texas Student Digital Humanities`,
  `Texas Student Psychological Association`,
  `Texas Students for The Well Austin`,
  `Texas Success for Austin Youth Organization`,
  `Texas Sunshines`,
  `Texas Sweethearts`,
  `Texas THON`,
  `Texas Table Tennis`,
  `Texas Table Top`,
  `Texas Taekwondo`,
  `Texas Tai Chi`,
  `Texas Talaash`,
  `Texas Taylor Swift Appreciation Society`,
  `Texas Theme Park Engineering and Design`,
  `Texas Tower Public Relations`,
  `Texas Transfer Students`,
  `Texas Trap and Skeet`,
  `Texas Trees for Change`,
  `Texas Triathlon & Cycling`,
  `Texas Trophy Hunters Association Chapter at UT`,
  `Texas UNICEF`,
  `Texas Undergraduate Investment Team`,
  `Texas Undergraduate Law Journal`,
  `Texas Undergraduate Moot Court Team`,
  `Texas Undergraduate Real Estate Society`,
  `Texas Undergraduate Research Journal`,
  `Texas Undergraduate Sales Organization`,
  `Texas Visual Arts Collective`,
  `Texas Wake`,
  `Texas Wesley UMCM`,
  `Texas Women in Economics`,
  `Texas Women's Club Lacrosse`,
  `Texas Women's Rugby`,
  `Texas Wranglers`,
  `Texas Wushu`,
  `Texas for Tots`,
  `Thai Association of Austin`,
  `The ATX Review at The University of Texas`,
  `The Alexander Hamilton Society at UT Austin`,
  `The Alzheimer's and Dementia Organization at The University of Texas at Austin`,
  `The Association of Black Psychologists`,
  `The Austin Bi+ Collective`,
  `The Austin Meal Movement`,
  `The Center for Students in Recovery`,
  `The Chi Phi Fraternity`,
  `The Corral`,
  `The E. Lee Walker Fellowship at Texas`,
  `The Feminist Policy Alliance`,
  `The Fruits`,
  `The Latino Pan-Hellenic Council`,
  `The Longhorn Rocketry Association`,
  `The National Association of Black Accountants at The University of Texas at Austin`,
  `The Negative Emissions Technology Project at UT Austin`,
  `The Onyx Honor Society`,
  `The Pans of Texas`,
  `The Ransom Notes`,
  `The Space - ATX`,
  `The Students of East Africa`,
  `The Tejas Club`,
  `The Texas Business Law Society`,
  `The Texas Law Aggie Society`,
  `The Texas Orator`,
  `The Thomistic Institute at UT Austin`,
  `The Triple Helix at UT Austin`,
  `The Undergraduate Art History Association`,
  `The Unfinished Mind Podcast`,
  `The University of Texas at Austin Student Foundation`,
  `Theta Chi Fraternity`,
  `Theta Tau - Professional Engineering Fraternity`,
  `Title IX Office`,
  `Turing Scholars Student Association`,
  `Turning Point USA at The University of Texas at Austin`,
  `Type Texas: The CDN Chapter at UT Austin`,
  `Tzu Chi Collegiate Association Austin Chapter`,
  `UBUNTU`,
  `UKirk Longhorn Presbyterian Fellowship`,
  `UNIVERSITY POLICE ORGANIZATION`,
  `UT Archery`,
  `UT Austin Geophysical Society`,
  `UT Badminton Club`,
  `UT Dance Team`,
  `UT Fencing Club`,
  `UT General Interest`,
  `UT ITF Taekwondo Team`,
  `UT Men's Soccer Team`,
  `UT Men's Ultimate Club`,
  `UT Nursing Students' Association`,
  `UT Quantum Collective`,
  `UT Racquetball Club`,
  `UT Sailing Team`,
  `UT Student Organization Advisors`,
  `UT Student Society of Health-System Pharmacists`,
  `UT Toastmasters Club for Students`,
  `UT Water Ski Team`,
  `UT Women's Club Soccer`,
  `UT Women's Volleyball Club`,
  `UT Women's Water Polo`,
  `UT Women's and Non-Binary Ultimate Frisbee`,
  `UTalent Records`,
  `UTeach Liberal Arts Student Group`,
  `UTeach-Liberal Arts`,
  `UX Design Club at the University of Texas at Austin`,
  `UXPA at UT Austin`,
  `Undergraduate Art History Association`,
  `Undergraduate Business Council`,
  `Undergraduate Chemical Engineering Women`,
  `Undergraduate Computational Finance Team`,
  `Undergraduate Exploratory Council`,
  `Undergraduate Geological Society`,
  `Undergraduate Korean Association`,
  `Undergraduate Mock Trial Association`,
  `United Mission for Relief & Development Texas Chapter`,
  `University Blood Initiative at UT Austin`,
  `University Democrats`,
  `University Fashion Group`,
  `University Finance Association`,
  `University Leadership Initiative`,
  `University Management & Business Research Association`,
  `University Panhellenic Council`,
  `University Residence Hall Association`,
  `University Securities Investment Team`,
  `University Theatre Guild`,
  `University Yoga Club`,
  `University of Texas - American Pharmacists Association - Academy of Student Pharmacists`,
  `University of Texas Amateur Radio Club`,
  `University of Texas Guild of Carillonneurs`,
  `University of Texas Sport Club Association`,
  `University of Texas Weightlifting Team`,
  `University of Texas at Austin Police Department (UTPD)`,
  `Unmanned Aerial Vehicle Team`,
  `Uplift Austin at Univeristy of Texas at Austin`,
  `VAW Global Health Alliances at the University of Texas at Austin`,
  `Valley Alliance of Mentors for Opportunities and Scholarships`,
  `Vamos Tennis`,
  `Vector Student Engineering Magazine`,
  `Vietnamese Students Association`,
  `Vocal Horns A Cappella`,
  `Voices of Afrika`,
  `Vow Ignite`,
  `Wealth Management Student Organization`,
  `West Campus Neighborhood Association`,
  `Women in Aerospace for Leadership and Development`,
  `Women in Business Association`,
  `Women in Cinema`,
  `Women in Civil, Architectural, and Environmental Engineering`,
  `Women in Computer Science`,
  `Women in Electrical and Computer Engineering (Women in ECE)`,
  `Women in Engineering Program`,
  `Women in Foreign Affairs`,
  `Women in Gaming`,
  `Women in Informatics at The University of Texas at Austin`,
  `Women in Mechanical Engineering`,
  `Women in Medicine`,
  `Women in Petroleum and Geosystems Engineering`,
  `Women in Psychology`,
  `Women of Excellence`,
  `Women's Law Caucus`,
  `Women's Resource Agency of Student Government`,
  `Women's Transportation Seminar - Heart of Texas Student Chapter`,
  `Young Conservatives of Texas - University Chapter`,
  `Young Life College Fellowship`,
  `Zeta Beta Tau`,
  `Zeta Phi Beta Sorority, Incorporated - Omicron Theta Chapter`,
  `Zeta Psi Fraternity`,
  `Zeta Tau Alpha`,
  `Zobha`,
  `alpha Kappa Delta Phi Sorority, Inc.`,
  `e-NABLE at UT Austin`,
  `iPride at UT Austin`,
  `iSchool Doctoral Students Association`,
  `iSchool Undergraduate Student Council`,
  `“Consult Your Community- Texas Chapter`,
]