export const slugify = (str: string) => {
  return str.toLowerCase().replace(/\s+/g, '-');
}

export const collegeMajors = [
  "Accounting",
  "Acting",
  "Advertising",
  "Aerospace Engineering",
  "African and African Diaspora Studies",
  "Ald: Youth and Cmmty Stds/Urb Tchrs Eng Langart",
  "Ald: Youth and Commty Stds/Urb Tchrs Soc Stds",
  "American Studies",
  "Anthropology",
  "Architectural Engineering",
  "Architecture",
  "Art Education (Bfa)",
  "Art History",
  "Art History (BA)",
  "Arts and Entertainment Technologies",
  "Asian Cultures and Languages",
  "Asian Studies",
  "Astronomy (Bsast) (Option: Astronomy Honors)",
  "Astronomy (Bsast) (Option: Astronomy)",
  "Athletic Training",
  "Audiology (Aud)",
  "B A in Theatre and Dance/Plan II Honors Program",
  "Bachelor of Arts in Music - Emphasis in Composition",
  "Bachelor of Arts in Music - Emphasis in Music",
  "Bachelor of Arts in Theatre and Dance",
  "Bioch (Bsbioch) Optn Bioch Honors/Plan II/Health Profs",
  "Biochem (Bsbioch) (Optn: Biochem Hnrs)/Premed Dent Vet",
  "Biochemistry",
  "Biology (Bsa)",
  "Biomedical Engineering",
  "Business Analytics (Bba)",
  "Cell and Molecular Biology",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classical Langua/Plan I Honors Program",
  "Classical Languages",
  "Classical Studies",
  "Classics",
  "Communication Studies (Phd)",
  "Comparative Literature",
  "Composition",
  "Computational Engineering",
  "Computer Science",
  "Dance",
  "Data Science (Msds, Option III)",
  "Design",
  "Economics",
  "Educational Leadership and Policy",
  "Educational Psychology",
  "Electrical Engineering",
  "Electrical and Computer Engineering",
  "Energy and Earth Resources",
  "Energy and Earth Resources/Business Administration",
  "Engineering Mechanics",
  "English",
  "Environmental Engineering",
  "Environmental Science, Biological Sciences",
  "Environmental and Water Resources Engineering",
  "Exercise Science",
  "Finance",
  "French",
  "Geography",
  "Geological Sciences",
  "German",
  "Germanic Studies",
  "Global Policy Studies",
  "Government",
  "Health & Society/Plan I Honors Program",
  "Health Behavior and Health Education",
  "Health and Society",
  "History",
  "Human Development & Family Sciences",
  "Human Dimensions of Organizations",
  "Human Ecology, Entry-Level",
  "Humanities",
  "Information Studies",
  "Information, Risk, and Operations Management",
  "International Business",
  "Italian Studies",
  "Jazz",
  "Journalism (Bj)",
  "Kinesiology",
  "Latin American Studies",
  "Law",
  "Leadership in Diverse Settings (Msn)",
  "Linguistics",
  "Management",
  "Marketing",
  "Materials Science and Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Medical Laboratory Science",
  "Microbiology",
  "Middle Eastern Languages and Cultures",
  "Music Composition",
  "Music Performance",
  "Neuroscience",
  "Nursing - Professional",
  "Nutrition (Bsa)",
  "Nutritional Sciences",
  "Operations Research and Industrial Engineering",
  "Petroleum Engineering",
  "Pharmaceutical Sciences",
  "Philosophy",
  "Physics",
  "Plan II Honors Program",
  "Professional Accounting",
  "Psychology",
  "Public Affairs",
  "Public Health",
  "Radio-Television-Film (Bsrtf)",
  "Religious Studies",
  "Rhetoric and Writing",
  "Russian, East European, and Eurasian Studies",
  "Science and Technology Management",
  "Science, Technology, Engineering, and Mathematics Educ",
  "Social Work",
  "Sociology",
  "Special Education",
  "Sport Management",
  "Statistics",
  "Studio Art",
  "Supply Chain Management",
  "Sustainability Studies",
  "Textiles and Apparel, Entry-Level",
  "Theatre & Dance",
  "Theatre Studies",
  "Undeclared",
  "Urban Studies",
  "Visual Art Studies",
  "Women's and Gender Studies",
] 